coffee-bean-blog/coffee-bean-blog-web/src/main/java/de/dksc0der/cbb/web/controller/LoginController.java
package de.dksc0der.cbb.web.controller;

import java.sql.Timestamp;

import javax.annotation.PostConstruct;
import javax.annotation.security.RolesAllowed;
import javax.ejb.EJB;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

import org.jboss.logging.Logger;

import de.dksc0der.cbb.model.Member;
import de.dksc0der.cbb.repository.MemberSecurityService;
import de.dksc0der.cbb.util.AppConstants;
import de.dksc0der.cbb.web.util.Resources;

@ManagedBean
@RequestScoped
public class LoginController {
	
	private static Logger log = Logger.getLogger(LoginController.class.getName());
	
	private static final String NAV_INDEX_REDIRECT = "/views/index?faces-redirect=true";
	
	@Inject
	private FacesContext facesContext;
	
	@EJB
	private MemberSecurityService securityServcie;
	
	private String username;
	private String password;
	
	private Member currentMember;
	
	@PostConstruct
	private void initialize(){
		ExternalContext externalContext = facesContext.getExternalContext();
		currentMember = (Member)externalContext.getSessionMap().get("member");
		
		if(currentMember == null){
			HttpServletRequest request = (HttpServletRequest)externalContext.getRequest();
			java.security.Principal principal = request.getUserPrincipal();
			if(principal != null){
				try {
					currentMember = securityServcie.findByUsername(principal.getName());
				} catch (Exception ignored) {
					try {
						((HttpServletRequest)externalContext.getRequest()).logout();
					} catch (ServletException alsoIngnored) {}
				}
			}
		}
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	public boolean isLoggedIn(){
		return currentMember != null;
	}
	
	public boolean isAdmin(){
		if(currentMember == null)
			return false;
		return currentMember.isAdmin();
	}
	
	public boolean isMemberUnverified(){
		if(currentMember == null)
			return false;
		return currentMember.isMemberUnverified();
	}
	
	public boolean isMemberVerified(){
		if(currentMember == null)
			return false;
		return currentMember.isMemberVerified();
	}
	
	public String login() throws Exception{
		ExternalContext externalContext = facesContext.getExternalContext();
		HttpServletRequest request = (HttpServletRequest)externalContext.getRequest();
		
		if(request.getUserPrincipal() == null){
			try {
				request.login(username, password);
				log.info(username + " logged in " + new Timestamp(System.currentTimeMillis()));
				currentMember = securityServcie.findByUsername(username);
				
				currentMember = securityServcie.beginSession(currentMember);
				
				externalContext.getSessionMap().put("member", currentMember);
				
				
				log.info("Logged Member -->> \n" + externalContext.getSessionMap().get("member"));
				return NAV_INDEX_REDIRECT;
			} catch (ServletException ignored) {
				facesContext.addMessage(null, new FacesMessage("Login Failed!!!", ""));
				return NAV_INDEX_REDIRECT;
			}
		}
		return NAV_INDEX_REDIRECT;
	}
	
	@RolesAllowed({AppConstants.ROLE_MEMBER_VERIFIED, AppConstants.ROLE_MEMBER_UNVERIFIED})
	public String logout() throws Exception{
		ExternalContext externalContext = facesContext.getExternalContext();
		HttpServletRequest request = (HttpServletRequest)externalContext.getRequest();
		
		try {
			if(request.getSession().getAttribute("member") != null){
				Member member = ((Member)request.getSession().getAttribute("member"));
				securityServcie.endSession(member);
				
				
				request.logout();
				externalContext.invalidateSession();
				currentMember = null;
				log.info("Logged out Member -->> \n" + externalContext.getSessionMap().get("member"));
			}
		} catch (ServletException e) {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Logout failed!!!", Resources.getRootErrorMessage(e)));
			return null;
		}
		return NAV_INDEX_REDIRECT;
	}
	
//	private String findMemberIP(HttpServletRequest request){
//		String ipAddress = request.getHeader("X-FORWARDED-FOR");
//		if(ipAddress != null){
//			ipAddress = ipAddress.replaceFirst(",.*", "");
//		}else{
//			ipAddress = request.getRemoteAddr();
//		}
//		return ipAddress;
//	}
}

coffee-bean-blog/coffee-bean-blog-web/src/main/webapp/views/templates/elements/content_control_template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:b="http://bootsfaces.net/ui">

<!-- 
		Replace path to template, title, header and body
		with actual data.
	 -->
<ui:composition>
	<b:row>
		<b:column col-lg="11" col-md="11" col-sm="12" col-xs="12"
			offset-lg="1" offset-md="1" style="">

			<b:row rendered="#{loginController.loggedIn}">
				<b:column style="margin-top: 20px;">
					<h5>Information</h5>
					<h:outputText value="Angemeldet als: " style="color: green;;" />
					<h:outputText value="#{sessionScope['member'].username}" />
				</b:column>
			</b:row>
			<b:row rendered="#{loginController.loggedIn}">
				<b:column style="margin-top: 0px;">
					<h:outputText value="Vorname: " style="color: green;;" />
					<h:outputText value="#{sessionScope['member'].firstname}" />
				</b:column>
			</b:row>
			<b:row rendered="#{loginController.loggedIn}">
				<b:column style="margin-top: 0px;">
					<h:outputText value="Nachname " style="color: green;;" />
					<h:outputText value="#{sessionScope['member'].lastname}" />
				</b:column>
			</b:row>
			<b:row rendered="#{loginController.loggedIn}">
				<b:column style="margin-top: 0px;">
					<h:outputText value="Geburtstag: " style="color: green;;" />
					<h:outputText value="#{sessionScope['member'].birthday}">
						<f:convertDateTime timeZone="CET" pattern="dd. MMMM yyyy" />
					</h:outputText>
				</b:column>
			</b:row>
			<b:row rendered="#{loginController.loggedIn}">
				<b:column style="margin-top: 0px;">
					<h:outputText value="Login: " style="color: green;;" />
					<h:outputText value="#{sessionScope['member'].lastLogout}">
						<f:convertDateTime pattern="dd.MM.yyyy hh:mm:ss" />
					</h:outputText>
				</b:column>
			</b:row>

			<b:row style="margin-top: 50px;">
				<b:column>
					<form>
						<h5>Suchen</h5>
						<input class="form-control" placeholder="Suchen..." id="filter"
							type="text" />
					</form>

				</b:column>
			</b:row>

			<b:row style="margin-top: 50px;">
				<b:column>
					<h5>Categories</h5>

					<ui:repeat value="#{indexController.categories}" var="value">
    					<h:form style="float: left;">
    						<h:commandLink update="@all" action="#{indexController.postsByCategory(value)}" value="#{value.categoryname}"/>&#160;&#160;
    					</h:form>
					</ui:repeat>
				</b:column>
			</b:row>

		</b:column>
		<h:outputScript library="js" name="sites/index/main.js" />
	</b:row>
</ui:composition>

</html>

coffee-bean-blog/coffee-bean-blog-web/src/main/webapp/views/templates/elements/footer_template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:ui="http://java.sun.com/jsf/facelets"
	  xmlns:f="http://java.sun.com/jsf/core"
	  xmlns:h="http://java.sun.com/jsf/html"
	  xmlns:b="http://bootsfaces.net/ui">

<ui:composition>
	<b:container id="footer_container" >
		<div id="linklist">
		<ul>
		<li><h:link id="impressum" value="#{la['footer.impressum']}"/></li>
		<li><h:link id="contact" value="#{la['footer.contact']}"/></li>
		<li><h:link id="aboutme" value="#{la['footer.aboutme']}"/></li>
		
		</ul>
			<div style="text-align: center; margin-top: 0px; font-size: 10px;">
				#{la['footer.copyrigt']}
			</div>
		</div>
	</b:container>
	<b:container style="width: 100%; height: 15px;"/>
</ui:composition>

</html>

coffee-bean-blog/coffee-bean-blog-web/src/main/webapp/views/templates/elements/header_template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">

<ui:composition>
	<b:container fluid="true" id="image-container">
		<b:carousel >
			<b:carouselItem>
     			<b:image id="header_image" library="img" name="banner/coffee_banner.png"  />
   			</b:carouselItem>
		</b:carousel>
	</b:container>
	<b:navBar brand="#{la['application.name']}" style="" brand-style="font-size: 50px;"
		brandHref="/coffee-bean-blog-web/views/index.xhtml" inverse="true"
		static="false" sticky="true" brand-style-class="font-brand">
		<b:navbarLinks>
			<b:navLink value="#{la['header.link.home']}"
				href="/coffee-bean-blog-web/views/index.xhtml"></b:navLink>
			<b:dropMenu value="#{la['header.link.member']}" rendered="#{loginController.memberVerified}">
				<b:navLink value="#{la['header.member.account']}"
				href="/coffee-bean-blog-web/views/account/account.xhtml"
				rendered="#{loginController.memberVerified}">
				</b:navLink>
				
				<b:navLink value="#{la['header.member.setting']}"
				href="#" 
				rendered="#{loginController.memberVerified}">
				</b:navLink>
				<b:navLink></b:navLink>
				
				<b:navLink value="#{la['header.member.admin']}"
				href="/coffee-bean-blog-web/views/account/admin/admin.xhtml"
				rendered="#{loginController.admin}">
				</b:navLink>
				<b:navLink></b:navLink>
			</b:dropMenu>
		</b:navbarLinks>
		<b:navbarLinks pull="right" style="margin-right: 0px;">
			<b:navLink value="#{la['header.link.verification']}"
			href="/coffee-bean-blog-web/views/verification/verificator.xhtml"
			rendered="#{loginController.memberUnverified}">
			</b:navLink>
			<b:dropMenu value="#{la['header.link.login']}" rendered="#{!loginController.loggedIn}">
				<b:container style="width: 20em;">

					<h:form styleClass="form-signin" prependId="false">
						<h6 class="form-signin-heading">#{la['header.login.title']}</h6>

						<b:inputText value="#{loginController.username}" id="username" style="font-size: 12px;"
							placeholder="#{la['header.login.username']}">
							<f:facet name="prepend">
								<b:icon name="user" />
							</f:facet>
						</b:inputText>

						<b:inputSecret  value="#{loginController.password}" id="password" style="font-size: 12px;"
							placeholder="#{la['header.loging.password']}" >
							<f:facet name="prepend">
								<b:iconAwesome name="key" />
							</f:facet>
						</b:inputSecret>

						<div id="forget_password_container">
							<a class="forget_password" href="/coffee-bean-blog-web/views/password/recovery.xhtml">#{la['header.login.forget']}</a>
						</div>
						
						<b:commandButton look="success btn-block" value="#{la['header.login.button.login']}"
							icon="log-in" size="sm" action="#{loginController.login()}" />
					</h:form>
					<b:button look="warning btn-block" icon-awesome="user-plus" size="sm" value="#{la['header.login.button.register']}"
						onclick="window.location.href='/coffee-bean-blog-web/views/register.xhtml'"></b:button>
					<br />
				</b:container>
			</b:dropMenu>
			<b:dropMenu value="#{la['header.link.logout']}" rendered="#{loginController.loggedIn}">
				<b:container style="width: 200px;">
					<h:form styleClass="form-signin" prependId="true">
						<h6 class="form-signin-heading">#{la['header.logout.title']}</h6>
						<b:commandButton look="danger btn-block" value="#{la['header.logout.button.logout']}"
							icon="log-out" size="sm" action="#{loginController.logout()}" />
					</h:form>
				</b:container>
			</b:dropMenu>
		</b:navbarLinks>
	</b:navBar>
</ui:composition>

</html>